In [9]:
# =================================================
# Milestone 1 Phase 0

# Nama  : Muhammad Adam Alhafizh
# Batch : CODA-RMT-003

# Program ini dibuat untuk melakukan extract, transform, dan load (ETL) dari suatu website yang nantinya akan digunakan untuk analisa lebih lanjut.
# =================================================

In [10]:
from selenium import webdriver # Untuk extract data
from bs4 import BeautifulSoup # Untuk memparsing/memecahkan data
import pandas as pd

Card HTML Element:
<div class="product-card product-grid__card  css-1tmiin5" data-product-position="2" data-testid="product-card"><div class="product-card__body" data-el-type="Card" data-testid="product-card__body"><figure><a class="product-card__link-overlay" data-testid="product-card__link-overlay" href="https://www.nike.com/id/t/vomero-17-road-running-shoes-49tSC9/FB8502-006" tabindex="-1">Nike Vomero 17</a><a aria-label="Nike Vomero 17" class="product-card__img-link-overlay" data-el-type="Hero" data-testid="product-card__img-link-overlay" href="https://www.nike.com/id/t/vomero-17-road-running-shoes-49tSC9/FB8502-006"><div class="wall-image-loader  css-1la3v4n" data-testid="wall-image-loader"><img alt="undefined undefined" class="product-card__hero-image css-1fxh5tw" height="100%" loading="eager" sizes="" src="https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a59b02ac-0c08-4454-afd0-014e05612633/W+NIKE+VOMERO+17.png" width="100%"><noscript><img alt="undefined undefined" class="product-card__hero-image css-1fxh5tw" height="400" loading="lazy" width="400"/></noscript></div></a><div class="product-card__info disable-animations has--percent-off"><div class="product_msg_info"><div class="product-card__titles"><div class="product-card__title" id="Nike Vomero 17" role="link">Nike Vomero 17</div><div class="product-card__subtitle" role="link">Women's Road Running Shoes</div></div></div><div class="product-card__count-wrapper show--all false" data-testid="product-card__count-wrapper "><div class="product-card__count-item"><button aria-disabled="false" aria-expanded="false" class="product-card__colorway-btn" data-testid="product-card__colorway-btn" type="button"><div aria-label="Available in 5 Colors" class="product-card__product-count">5 Colours</div></button></div></div><div class="product-card__animation_wrapper"><div class="product-card__price-wrapper"><div class="product-card__price" data-testid="product-card__price" role="link"><div aria-label="current price Rp&nbsp;1,988,000, original price Rp&nbsp;2,489,000" class="product-price__wrapper css-9xqpgk"><div aria-hidden="true" class="product-price is--current-price css-1ydfahe" data-testid="product-price-reduced">Rp&nbsp;1.988.000</div><div aria-hidden="true" class="product-price id__styling is--striked-out css-0" data-testid="product-price">Rp&nbsp;2.489.000</div></div><div class="product-price__perc css-1rz91t">20% off</div></div></div></div></div></figure></div></div>

Nama Produk:
<div class="product-card__title" id="Nike Vomero 17" role="link">Nike Vomero 17</div>

Harga Produk:
<div aria-hidden="true" class="product-price is--current-price css-1ydfahe" data-testid="product-price-reduced">Rp&nbsp;1.988.000</div>

Harga Produk (Non-discount):
<div class="product-price id__styling is--current-price css-11s12ax" data-testid="product-price">Rp&nbsp;2.199.000</div>

Kategori Produk:
<div class="product-card__subtitle" role="link">Women's Road Running Shoes</div>

Jumlah Warna Produk:
<div aria-label="Available in 5 Colors" class="product-card__product-count">5 Colours</div>

In [11]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time

# Mendeklarasikan list kosong untuk masing-masing kolom
product_names = []
product_prices = []
product_categories = []
product_colors = []

# Mendeklarasikan chrome sebagai browser yang akan digunakan
driver = webdriver.Chrome()

# Mendeklarasikan url untuk masing-masing page 
url = f"https://www.nike.com/id/w?q=shoe&vst=shoe"
    
# Menjalankan chrome dengan link secara otomatis
driver.get(url)
html = driver.page_source
soup = BeautifulSoup(html, "html.parser")

In [12]:
# Menyimpan semua HTML element di variabel product_container
product_container = soup.find_all("div",{"data-testid":"product-card"})
# time.sleep(3)
# driver.execute_script('window.scrollBy(0, 100000)')
# time.sleep(5)


for container in product_container:
    
    # Mengambil data nama produk
    if container.find_all("div",{"class":"product-card__title"}) != None:
        product_names += [name.text for name in soup.find_all("div",{"class":"product-card__title"})] #product_names.append(container.find("div",{"class":"product-card__title"}).text)
    else:
        product_names += (None)

    # Mengambil data harga produk
    if container.find_all("div",{"data-testid":"product-price"}) != None:
        product_prices += [price.text for price in soup.find_all("div",{"data-testid":"product-price"})]
    elif container.find_all("div",{"data-testid":"product-price"}) != None:
        product_prices += [price.text for price in soup.find_all("div",{"data-testid":"product-price"})]
    else:
        product_prices += (None)
        
    # Mengambil data kategori produk
    if container.find_all("div",{"class":"product-card__subtitle"}) != None:
        product_categories += [category.text for category in soup.find_all("div",{"class":"product-card__subtitle"})]
    else:
        product_categories += (None)
        
    # Mengambil data jumlah warna produk
    if container.find_all("div",{"class":"product-card__product-count"}) != None:
        product_colors += [color.text for color in soup.find_all("div",{"class":"product-card__product-count"})]
    else:
        product_colors += (None)

In [13]:
# Me-limit semua data menjadi 100 row
max_length = 100
product_names = product_names[0:max_length]
product_prices = product_prices[0:max_length]
product_categories = product_categories[0:max_length]
product_colors = product_colors[0:max_length]

In [14]:
# Membuat dataframe dari masing-masing data yang sudah diambil
df = pd.DataFrame({"product_name":product_names,
                        "product_price":product_prices,
                        "product_category":product_categories,
                        "product_color":product_colors})

# Mendisplay sebagian data awal dar dataframe yang sudah dibuat
df.head(27)

        
# df_test

,product_name,product_price,product_category,product_color
0,Giannis Immortality 4,Rp 999.000,Older Kids' Basketball Shoes,8 Colours
1,Nike Vaporfly 3,Rp 3.399.000,Men's Road Racing Shoes,2 Colours
2,Nike Dunk Low Premium,Rp 2.099.000,Women's Shoes,2 Colours
3,Nike IsoFly,Rp 959.000,Older Kids' Basketball Shoes,5 Colours
4,Nike Court Vision Low,Rp 1.069.000,Men's Shoes,1 Colour
5,Nike Air Max Plus Premium,Rp 2.849.000,Men's Shoes,1 Colour
6,Nike P-6000,Rp 1.729.000,Women's Shoes,2 Colours
7,Nike Air Max 1 SP,Rp 2.489.000,Men's Shoes,1 Colour
8,Nike Cortez Textile,Rp 1.549.000,Women's Shoes,2 Colours
9,Nike Air Force 1 '07,Rp 1.549.000,Men's Shoe,1 Colour
10,Giannis Immortality 4 EP,Rp 1.199.000,Basketball Shoes,10 Colours
11,Nike Metcon 9,Rp 2.199.000,Women's Workout Shoes,3 Colours
12,NikeCourt Lite 4,Rp 1.149.000,Women's Tennis Shoes,5 Colours
13,Nike Air Force 1 '07,Rp 1.549.000,Men's Shoes,2 Colours
14,Nike Air Force 1 '07,Rp 1.549.000,Women's Shoes,3 Colours
15,Nike Tiempo Legend 10 Club,Rp 799.000,Multi-Ground Low-Top Football Boot,2 Colours
16,Nike Phantom Luna 2 Elite Electric,Rp 4.539.000,FG High-Top Football Boot,1 Colour
17,Nike Mercurial Superfly 10 Elite,Rp 4.329.000,FG High-Top Football Boot,4 Colours
18,Nike Pegasus 41,Rp 2.099.000,Men's Road Running Shoes,8 Colours
19,NikeCourt Lite 4,Rp 1.149.000,Men's Tennis Shoes,4 Colours
20,Nike Air Max Dn,Rp 1.759.000,Older Kids' Shoes,3 Colours
21,Nike Air Max Dn8,Rp 3.049.000,Men's Shoes,5 Colours
22,Nike Air Max Dn8,Rp 3.049.000,Women's Shoes,4 Colours
23,Nike Air Max Dn8,Rp 2.549.000,Older Kids' Shoes,1 Colour
24,Giannis Immortality 4,Rp 999.000,Older Kids' Basketball Shoes,8 Colours
25,Nike Vaporfly 3,Rp 3.399.000,Men's Road Racing Shoes,2 Colours
26,Nike Dunk Low Premium,Rp 2.099.000,Women's Shoes,2 Colours

In [15]:
# Mengambil angka total terjual dari HTML elemen yang menyimpan total barang terjual
new_price_column = df["product_price"].str.replace("Rp\xa0", "")
new_price_column = new_price_column.str.replace(".", "")
new_price_column = new_price_column.astype("int64")

# Menggabungkan kolom-kolom yang dibuat sebelumnya ke dataframe utama
df["product_price"] = new_price_column

In [16]:
# Mengimport data ke CSV
df.to_csv('shoe_data.csv', index=False)